Vagrant.configure(2) do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true

    # Jenkins master VM
    config.vm.define "master" do |master|
        master.vm.box = "rockylinux/9"
        master.vm.hostname = "jenkins.hariharanep.com"
        master.vm.network "private_network", ip: "192.168.56.12"
        master.vm.provider "virtualbox" do |vb|
            vb.name = "Jenkins Master"
            vb.memory = 1024
        end
    end

    # Jenkins slave VM
    config.vm.define "slave" do |slave|
        slave.vm.box = "rockylinux/9"
        slave.vm.hostname = "jenkins-slave.jenkins.hariharanep.com"
        slave.vm.network "private_network", ip: "192.168.56.13"
        slave.vm.provider "virtualbox" do |vb|
            vb.name = "Jenkins Slave"
            vb.memory = 1024
        end
    end
end