Vagrant.configure(2) do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true

    # Jenkins master VM
    config.vm.define "rocky" do |rocky|
        rocky.vm.box = "rockylinux/9"
        rocky.vm.hostname = "jenkins.hariharanep.com"
        rocky.vm.network "private_network", ip: "192.168.56.12"
        rocky.vm.provider "virtualbox" do |vb|
            vb.name = "Jenkins Master"
            vb.memory = 1024
        end
    end

    # Jenkins slave VM
    config.vm.define "rocky" do |rocky|
        rocky.vm.box = "rockylinux/9"
        rocky.vm.hostname = "jenkins-slave.jenkins.hariharanep.com"
        rocky.vm.network "private_network", ip: "192.168.56.13"
        rocky.vm.provider "virtualbox" do |vb|
            vb.name = "Jenkins Slave"
            vb.memory = 1024
        end
    end
end