Vagrant.configure(2) do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true

    # Rocky Linux VM
    config.vm.define "rocky" do |rocky|
        rocky.vm.box = "rockylinux/9"
        rocky.vm.hostname = "monitoring.hariharanep.com"
        rocky.vm.network "private_network", ip: "192.168.56.11"
        rocky.vm.provider "virtualbox" do |vb|
            vb.name = "Rocky Linux"
            vb.memory = 2048
        end
    end
end